# Generated by Django 4.0.3 on 2022-04-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_created_alter_post_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
